package puzzle.ui;

import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

@SuppressWarnings("serial")
public class WordPanel extends JPanel {
	private JButton submitButton; //The button that will submit the length of target words to the controller
	private JSpinner lengthSpinner;
	private JList<String> wordList;
	private JScrollPane wordPane;
	private JLabel timeLabel;
	
	/*...*/
	public WordPanel(){
		super();
		/*
		 * If you want to use JList, init the JList with an empty arrayList
		 * 
		 * It's better not to use AbstractModel class or any other Model class for this JList.(We used AbstractModel in 120) 
		 * Instead, use jlist.setListData in the actionListener every time the content changes.
		 * 
		 * Because AbstractModel class requires a persistent list variable. However, the valid word list generated by the 
		 * model section of the program will not be a class variable. In other word, every time the findValidWords 
		 * method get called, a completely new arraylist will be generated. 
		 * 
		 * 
		 */
		
		lengthSpinner = new JSpinner(new SpinnerNumberModel(2, 2, 2, 1));
		lengthSpinner.setSize(new Dimension(200,20));
		lengthSpinner.setMinimumSize(new Dimension(50,20));
		lengthSpinner.setPreferredSize(new Dimension(50,20));
		
		submitButton = new JButton("Submit");
		
		wordPane = new JScrollPane();
		wordList = new JList<String>();
		
		wordPane.setViewportView(wordList);
		wordPane.setPreferredSize(new Dimension(480,400));
		
		timeLabel = new JLabel("TIME ELAPSED: ");
		
		add(lengthSpinner);
		add(submitButton);
		add(wordPane);
		add(timeLabel);
		
	}
	
	public JScrollPane getScrollPane(){
		return wordPane;
	}
	
	public JSpinner getSpinner(){
		return lengthSpinner;
	}
	
	public JList<String> getList(){
		return wordList;
	}
	
	public JButton getSubmit() {
		return submitButton;
	}
	
	
	
}
